"""Update timetable model for CSV import

Revision ID: 4d9139cfe04c
Revises: 0f97a0ff9e61
Create Date: 2026-08-20 22:13:17.025237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d9139cfe04c'
down_revision = '0f97a0ff9e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_receiver_read', ['receiver_type', 'receiver_id', 'is_read'], unique=False)
        batch_op.create_index('idx_chat_sender_read', ['sender_type', 'sender_id', 'is_read'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notif_user_read', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.create_index('idx_booking_status_slot', ['status', 'slot_start'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('idx_room_floor', ['floor_id'], unique=False)

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=50), nullable=True))
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_timetable_day_start', ['day_of_week', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index('idx_timetable_day_start')
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('division')
        batch_op.drop_column('course')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('idx_room_floor')

    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_index('idx_booking_status_slot')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notif_user_read')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_sender_read')
        batch_op.drop_index('idx_chat_receiver_read')

    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('schedules_faculty_id_fkey')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('schedules_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    # ### end Alembic commands ###
