"""add has_accepted_terms to user

Revision ID: 92ae55fe848e
Revises: af9f660411dd
Create Date: 2026-09-28 11:13:21.863675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ae55fe848e'
down_revision = 'af9f660411dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_accepted_terms', sa.Boolean(), server_default='false', nullable=False))

    # Explicitly enforce False for all existing records so all pre-existing users are forced through the new compliance gate
    op.execute("UPDATE users SET has_accepted_terms = FALSE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_accepted_terms')

    # ### end Alembic commands ###
