"""add event booking and update notification

Revision ID: af9f660411dd
Revises: 0609ec198727
Create Date: 2026-09-22 16:37:51.413810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af9f660411dd'
down_revision = '0609ec198727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('booking_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_bookings', schema=None) as batch_op:
        batch_op.create_index('idx_event_start_end', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_event_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_bookings_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_bookings_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_bookings_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_bookings_status'), ['status'], unique=False)

    op.create_table('event_floors',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'floor_number')
    )
    op.create_table('event_rooms',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'room_id')
    )
    op.drop_table('no_show_strikes')
    with op.batch_alter_table('adhoc_bookings', schema=None) as batch_op:
        batch_op.alter_column('checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_role', sa.String(length=30), server_default='admin', nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.alter_column('checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index('idx_booking_faculty_date', ['faculty_id', 'date'], unique=False)
        batch_op.create_index('idx_booking_room_slot', ['room_id', 'status', 'slot_start'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_room_status', ['room_id', 'status'], unique=False)

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_timetable_day_start'))
        batch_op.create_index('idx_timetable_collab', ['collaborator_id', 'day_of_week', 'start_time'], unique=False)
        batch_op.create_index('idx_timetable_lookup', ['faculty_id', 'day_of_week', 'start_time'], unique=False)
        batch_op.create_index('idx_timetable_room', ['room_id', 'day_of_week', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index('idx_timetable_room')
        batch_op.drop_index('idx_timetable_lookup')
        batch_op.drop_index('idx_timetable_collab')
        batch_op.create_index(batch_op.f('idx_timetable_day_start'), ['day_of_week', 'start_time'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('idx_ticket_room_status')

    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_index('idx_booking_room_slot')
        batch_op.drop_index('idx_booking_faculty_date')
        batch_op.alter_column('checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('recipient_role')

    with op.batch_alter_table('adhoc_bookings', schema=None) as batch_op:
        batch_op.alter_column('checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    op.create_table('no_show_strikes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strike_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('no_show_strikes_faculty_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('no_show_strikes_room_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('no_show_strikes_pkey'))
    )
    op.drop_table('event_rooms')
    op.drop_table('event_floors')
    with op.batch_alter_table('event_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_event_bookings_start_date'))
        batch_op.drop_index(batch_op.f('ix_event_bookings_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_event_bookings_end_date'))
        batch_op.drop_index('idx_event_status')
        batch_op.drop_index('idx_event_start_end')

    op.drop_table('event_bookings')
    # ### end Alembic commands ###
